name = input("Enter your Name : ")
Father = input("Enter your Father Name : ")
clas = input("Enter your class : ")
section = input("Enter your section : ")
eng = float(input("Enter English Marks : "))
urdu = float(input("Enter Urdu Marks : "))
math = float(input("Enter Maths Marks : "))
chem = float(input("Enter Chemistry Marks : "))
phy = float(input("Enter Physics Marks : "))
islam = float(input("Enter Islamiat Marks : "))
total = float(eng+urdu+math+chem+phy+islam)
per = float((total/600)*100)
print("\n\t\t *****Marksheet*****")
print("\n")
print(" Name : " + name.upper() + "\t\t Father Name : " + Father.upper())
print(" Class : " +  str(clas) + section + "\t\t")
print("\n")
print(" English \t:\t ", eng)
print(" Urdu \t\t:\t ", urdu)
print(" Maths \t\t:\t ", math)
print(" Physics \t:\t ", phy)
print(" Chemistry \t:\t ", chem)
print(" Islamiat \t:\t ", islam)
print("\n Marks Obtained : " + str(total) + "\t\t Percentage : ", per)

if per <= 100 and per >= 90:
    print(" Grade : A+")
    print(" Excellent " + name.upper())
elif per <= 90 and per >= 80:
    print(" Grade : A")
    print(" Weldone " + name.upper())
elif per <= 80 and per >= 70:
    print(" Grade : B")
    print(" Awesome " + name.upper())
elif per <= 70 and per >= 60:
    print(" Grade : C")
    print(" Better " + name.upper())
elif per <= 60 and per >= 50:
    print(" Grade : D")
    print(" Good " + name.upper())
else:
    print(" Grade : F")
    print(" Sorry you are Failed " + name.upper())
print("\n\t\t *****The End*****")